language: php

php:
    - 7.0
    - 7.1

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-dist"

matrix:
    fast_finish: true

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - travis_retry composer self-update

install:
    - travis_retry composer update --no-interaction --prefer-dist $COMPOSER_OPTS

script:
    - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
